intf_libs = # Interface dependencies.
import intf_libs += fmt%lib{fmt}
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{format}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
hxx{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBFORMAT_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBFORMAT_SHARED_BUILD

# Export options.
#
lib{format}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{format}: cxx.export.poptions += -DLIBFORMAT_STATIC
libs{format}: cxx.export.poptions += -DLIBFORMAT_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{format}: bin.lib.version = @"-$version.project_id"
else
  lib{format}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the libformat/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libformat/
  install.subdirs = true
}
